### PR TITLE
fix(sweep): wait for scheduler start/stop

### LINKED ISSUE #267: Wait for operation to start successfully on Jam screen
The Jam screen currently does not wait for an operation to start/stop and assumes the operation will succeed. This causes some delay and UI issues should the operation turn out to be unsuccessful. 

Use the same approach as in the Earn screen and wait for the server to signal the successful operation, ie. https://github.com/joinmarket-webui/joinmarket-webui/blob/a95ac7a6e419f52150a608e0b66c498240361db7/src/components/Earn.jsx#L156-L177

Related: https://github.com/joinmarket-webui/joinmarket-webui/issues/264

### PR DESCRIPTION
**Pull request by theborakompanioni**
Closes #267.

Before this PR, the Sweep screen did not wait for an operation to start/stop and assumed the operation will succeed.
After this PR, the screen will show a loading indicator till the service has been successfully started/stopped.

### CODE REVIEW

**Review by dergigi — APPROVED** [review]
Looks good to me, tACK ✅

File: src/components/Jam.jsx [hunk 1]
```diff
@@ -172,29 +185,34 @@ export default function Jam() {
...
   }
 
   return (
     <>
       <PageTitle title={t('scheduler.title')} subtitle={t('scheduler.subtitle')} />
       {alert && <rb.Alert variant={alert.variant}>{alert.message}</rb.Alert>}
 
-      {isLoading ? (
+      {isLoading || isWaitingSchedulerStart || isWaitingSchedulerStop ? (
         <rb.Placeholder as="div" animation="wave">
```
Comment (dergigi) [inline src/components/Jam.jsx:216]: Unrelated to this PR, but I thought I'd mention it anyway: I'm not sure how `animation="wave"` should look like, but this is how the loading state looks for me when starting/stopping the scheduler:

Screenshot 2022-10-03 at 18 27 31

Independent of the changes in this PR, and independent of browser (Firefox and Chromium).
